import Head from "next/head";
import Header from "./(design)/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Script from "next/script";
import Side from "./(design)/components/Side";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "homepage work",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <Script src="https://cdn.tailwindcss.com"></Script>
      <body className={inter.className}>
        <Header />
        <div className="flex">
          <div className="w-2/12">
            <Side />
          </div>
          <div className="w-10/12">
            <div className="p-5">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
